package com.foursys.fourcamp.alphabank.enums;

public enum BoPCodeEnum {

    DIRECT_INVESTIMENTS,  SECURITIES_INVESTMENT, LOANS, DEPOSITS, TRAVEL_SERVICES, MAILAND_TELECOMMUNICATIONS,
    TRANSPORT_SERVICES, ENTERTAINEMENT_SERVICES_AND_CULTURE, INSURANCE, DIVIDENTS_AND_CAPITAL_GAINS,
    RENTS_FOR_RESIDENTS_ABROAD, SCHOLARSHIPS, CREDIT_CARDS
}